// <auto-generated />
using System;
using LibraryApi.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20251128163546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApi.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nicholas Sparks",
                            CategoryId = 1,
                            Price = 100000,
                            PublicationYear = 1996,
                            Summary = "A deeply emotional romance about Noah and Allie, two young lovers whose relationship is torn apart by social differences. Their love endures across the years, revealing the power of memory, devotion, and second chances in a timeless story of heartfelt connection.",
                            Title = "The Notebook"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jojo Moyes",
                            CategoryId = 1,
                            Price = 150000,
                            PublicationYear = 2012,
                            Summary = "A touching and transformative romance between Louisa and Will, exploring themes of hope, independence, and the meaning of living fully. Their bond grows through emotional challenges that reshape both their lives in profound and unforgettable ways.",
                            Title = "Me Before You"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gillian Flynn",
                            CategoryId = 2,
                            Price = 100000,
                            PublicationYear = 2012,
                            Summary = "A psychological mystery centered on the disappearance of Amy Dunne and the growing suspicion around her husband. The story unfolds through unreliable narratives, dark secrets, and unexpected twists that keep readers guessing until the final reveal.",
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Stieg Larsson",
                            CategoryId = 2,
                            Price = 300000,
                            PublicationYear = 2005,
                            Summary = "A suspenseful investigation into corruption, murder, and hidden truths as journalist Mikael Blomkvist teams up with the brilliant yet troubled hacker Lisbeth Salander. Their search exposes a chilling family mystery with far-reaching consequences.",
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.K. Rowling",
                            CategoryId = 3,
                            Price = 250000,
                            PublicationYear = 1997,
                            Summary = "A magical adventure following Harry Potter as he discovers his true identity and enters the enchanting world of Hogwarts. Filled with wonder, friendship, danger, and destiny, this story begins an epic journey that has captivated millions worldwide.",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 3,
                            Price = 220000,
                            PublicationYear = 1937,
                            Summary = "Bilbo Baggins is unexpectedly drawn into an epic quest with dwarves, encountering trolls, goblins, and a dragon. A classic fantasy tale blending courage, discovery, and the enchanting landscapes of Middle-earth in an unforgettable adventure.",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Frank Herbert",
                            CategoryId = 4,
                            Price = 170000,
                            PublicationYear = 1965,
                            Summary = "A sweeping sci-fi epic set on the desert planet Arrakis, where political intrigue, ecological struggle, and spiritual awakening intertwine. Paul Atreides confronts destiny, power, and survival in a world shaped by conflict and ancient prophecy.",
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Andy Weir",
                            CategoryId = 4,
                            Price = 100000,
                            PublicationYear = 2011,
                            Summary = "Astronaut Mark Watney is stranded on Mars and must rely on ingenuity, engineering, and sheer determination to survive. A gripping survival story combining science, humor, and human resilience against overwhelming odds.",
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Stephen King",
                            CategoryId = 5,
                            Price = 330000,
                            PublicationYear = 1986,
                            Summary = "A terrifying tale of a shape-shifting entity feeding on fear in the town of Derry. A group of children face their darkest nightmares, forming bonds that stretch into adulthood as they confront an ancient evil haunting their lives.",
                            Title = "It"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Shirley Jackson",
                            CategoryId = 5,
                            Price = 179000,
                            PublicationYear = 1959,
                            Summary = "A chilling exploration of psychological terror as a group investigates a mysterious mansion. The house seems alive with sinister intent, blurring the line between supernatural danger and the fragile minds of its occupants.",
                            Title = "The Haunting of Hill House"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Dan Brown",
                            CategoryId = 6,
                            Price = 200000,
                            PublicationYear = 2003,
                            Summary = "A fast-paced thriller combining art, religion, and secret societies. Symbologist Robert Langdon unravels cryptic clues across Europe, racing against time to uncover a hidden truth that could shake the foundations of history.",
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Paula Hawkins",
                            CategoryId = 6,
                            Price = 100000,
                            PublicationYear = 2015,
                            Summary = "A suspenseful psychological thriller following Rachel, a troubled woman entangled in a missing-person case. As her fragmented memories collide with disturbing revelations, the truth becomes increasingly dangerous and shocking.",
                            Title = "The Girl on the Train"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Anthony Doerr",
                            CategoryId = 7,
                            Price = 99000,
                            PublicationYear = 2014,
                            Summary = "A beautifully written WWII story following a blind French girl and a German boy whose lives converge. Through hardship, war, and moral struggle, their journeys highlight courage, innocence, and the resilience of the human spirit.",
                            Title = "All the Light We Cannot See"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Markus Zusak",
                            CategoryId = 7,
                            Price = 160000,
                            PublicationYear = 2005,
                            Summary = "Narrated by Death, this story follows a young girl in Nazi Germany who finds solace in books during times of fear and loss. Her acts of reading and sharing stories bring hope to those around her despite the darkness of war.",
                            Title = "The Book Thief"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Khaled Hosseini",
                            CategoryId = 8,
                            Price = 100000,
                            PublicationYear = 2007,
                            Summary = "A powerful and emotional journey of two Afghan women whose lives intertwine through oppression, loss, and unexpected sisterhood. Their courage and enduring strength form a deeply moving story of sacrifice and resilience.",
                            Title = "A Thousand Splendid Suns"
                        },
                        new
                        {
                            Id = 16,
                            Author = "John Green",
                            CategoryId = 8,
                            Price = 210000,
                            PublicationYear = 2012,
                            Summary = "A tender and emotional drama following Hazel and Gus—two teens facing illness while discovering love, hope, and meaning. Their story examines grief, connection, and the beauty found even in life’s most fragile moments.",
                            Title = "The Fault in Our Stars"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Robert Louis Stevenson",
                            CategoryId = 9,
                            Price = 550000,
                            PublicationYear = 1883,
                            Summary = "A classic adventure about young Jim Hawkins, who sets sail in search of buried treasure. Pirates, danger, and high-seas excitement shape his journey, making it one of the most iconic tales of exploration and bravery.",
                            Title = "Treasure Island"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Arthur Conan Doyle",
                            CategoryId = 9,
                            Price = 480000,
                            PublicationYear = 1912,
                            Summary = "An expedition led by Professor Challenger discovers a hidden plateau where dinosaurs still roam. The team faces peril, wonder, and prehistoric life in a thrilling adventure filled with danger and discovery.",
                            Title = "The Lost World"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Terry Pratchett & Neil Gaiman",
                            CategoryId = 10,
                            Price = 6300000,
                            PublicationYear = 1990,
                            Summary = "A comedic and imaginative story about an angel and a demon who join forces to prevent the apocalypse. Filled with quirky humor, clever satire, and memorable characters, the novel blends chaos with charm in a hilarious journey.",
                            Title = "Good Omens"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Douglas Adams",
                            CategoryId = 10,
                            Price = 390000,
                            PublicationYear = 1979,
                            Summary = "A wildly funny sci-fi comedy where Arthur Dent is thrust into a bizarre galactic adventure. Absurd situations, witty dialogue, and cosmic nonsense create an unforgettable journey through a chaotic universe.",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Dennis Lehane",
                            CategoryId = 11,
                            Price = 250000,
                            PublicationYear = 2003,
                            Summary = "A tense psychological mystery in which U.S. Marshal Teddy Daniels investigates a missing patient on an isolated asylum island. As haunting clues emerge, the line between reality and illusion becomes dangerously blurred.",
                            Title = "Shutter Island"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Alex Michaelides",
                            CategoryId = 11,
                            Price = 410000,
                            PublicationYear = 2019,
                            Summary = "A gripping psychological drama about Alicia, a woman who stops speaking after a shocking crime. A psychotherapist becomes obsessed with discovering the reason behind her silence, uncovering hidden truths along the way.",
                            Title = "The Silent Patient"
                        });
                });

            modelBuilder.Entity("LibraryApi.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Romance stories focus on deep emotions, romantic tension, and the growing attraction between two characters.\nThese books draw readers into a world of longing, excitement, and heartfelt moments that often lead to a soothing reunion or a lasting love.",
                            Name = "romance"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mystery stories revolve around suspense, hidden clues, and the pursuit of uncovering the truth.\nThese books keep readers engaged through tension-filled twists and revelations that build toward a satisfying conclusion.",
                            Name = "mystery"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fantasy tales transport readers to magical realms filled with mythical creatures, powerful forces, and epic quests.\nThey offer immersive worlds where imagination thrives and heroes rise against extraordinary challenges.",
                            Name = "fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Science fiction explores futuristic technologies, advanced worlds, and the possibilities of scientific discovery.\nThese stories ignite curiosity by blending innovation with adventure and philosophical questions about humanity.",
                            Name = "science fiction"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Horror stories evoke fear, tension, and psychological unease through dark atmospheres and unsettling events.\nThey captivate readers with chilling twists that tap into primal emotions and hidden fears.",
                            Name = "horror"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Thrillers are driven by intense pacing, high stakes, and constant suspense that keeps readers on edge.\nThese books create gripping narratives filled with danger, urgency, and unexpected turns.",
                            Name = "thriller"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Historical fiction blends factual settings with imaginative storytelling rooted in real events or eras.\nThese novels immerse readers in rich atmospheres while offering insight into cultures and times long past.",
                            Name = "historical fiction"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Drama stories center on emotional conflict, personal struggles, and complex relationships among characters.\nThey provide stirring narratives that explore growth, resilience, and human connection.",
                            Name = "drama"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Adventure tales follow daring quests, perilous journeys, and the spirit of exploration across unknown lands.\nThey draw readers into fast-paced experiences fueled by courage, discovery, and excitement.",
                            Name = "adventure"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Comedy stories aim to entertain through humor, witty dialogue, and amusing situations.\nThese books lift the reader’s spirit with lighthearted moments and playful character dynamics.",
                            Name = "comedy"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Psychological stories delve into the complexities of the human mind, inner conflicts, and emotional depth.\nThey offer thoughtful narratives that challenge perception and explore the boundaries of consciousness.",
                            Name = "psychological"
                        });
                });

            modelBuilder.Entity("LibraryApi.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LibraryApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("LibraryApi.Entities.Book", b =>
                {
                    b.HasOne("LibraryApi.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryApi.Models.OrderItem", b =>
                {
                    b.HasOne("LibraryApi.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LibraryApi.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryApi.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
